import type { Metadata } from "next";
import "./globals.css";
import { fontBold, fontRegular, fontSemiBold } from "@/functions/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${fontBold.variable} ${fontRegular.variable} ${fontSemiBold.variable} app`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
